-- 测试video接口的示例数据
INSERT INTO video (
    id, created_at, updated_at, title, is_recommend, is_show, cover, description, content,
    author_avatar, author_name, author_intro, external_link, code, duration, type, datetime, uid, view_count, status
) VALUES
(
    '1000000000000001',
    NOW(),
    NOW(),
    'Go语言入门教程',
    1,
    1,
    'https://example.com/cover1.jpg',
    '这是一个关于Go语言基础入门的视频教程，适合初学者学习。',
    '# Go语言入门教程\n\n本视频将带你从零开始学习Go语言...',
    'https://example.com/avatar1.jpg',
    '张老师',
    'Go语言资深开发者，5年开发经验',
    'https://www.youtube.com/watch?v=example1',
    'GO_TUTORIAL_001',
    3600,
    'tutorial',
    NOW(),
    '1',
    0,
    1
),
(
    '1000000000000002',
    NOW(),
    NOW(),
    'React开发实战',
    1,
    1,
    'https://example.com/cover2.jpg',
    '从零到一构建React应用，包含最新的React Hooks使用方法。',
    '# React开发实战\n\n本课程将教你如何使用React构建现代化的Web应用...',
    'https://example.com/avatar2.jpg',
    '李老师',
    '前端开发专家，React核心贡献者',
    'https://www.youtube.com/watch?v=example2',
    'REACT_ADVANCED_002',
    5400,
    'advanced',
    NOW(),
    '2',
    15,
    1
),
(
    '1000000000000003',
    NOW(),
    NOW(),
    '数据库设计原理',
    2,
    1,
    'https://example.com/cover3.jpg',
    '深入理解数据库设计原理，掌握高效的数据库设计方法。',
    '# 数据库设计原理\n\n本视频将深入讲解数据库设计的核心原理...',
    'https://example.com/avatar3.jpg',
    '王老师',
    '数据库架构师，10年数据库设计经验',
    'https://www.youtube.com/watch?v=example3',
    'DB_DESIGN_003',
    4800,
    'theory',
    NOW(),
    '3',
    8,
    1
);
